### ISSUE TITLE
[Check] XXE checks for JavaScript

### ISSUE THREAD

**Issue by minusworld** [returntocorp/semgrep-rules#508]
**Check Description**
XXE checks for JavaScript, if applicable.

- [x] This ticket has links, references, or examples.
- [x] Your check has true positive and true negative test cases.
- [x] Your check has been labeled with true positive and false positive findings on at least 10 repositories, and the link is pasted in the ticket. If there are no findings, paste the triager link anyway.
- [x] Your check PR has been reviewed and merged.
Now, close the ticket!

**Comment by inkz** [comment]
`node-expat` module and it's dependent `xml2json` allow XXE in some way, (e.g. Billion Laugh Attack)
so the patterns to cover this situation were created

also the most popular module for xml parsing - `sax` was covered with the set of patterns in order to identify weak part wich is reading DTD definitions, which if handled irresponsibly may lead to XXE

https://www.npmjs.com/package/node-expat
https://www.npmjs.com/package/xml2json
https://www.npmjs.com/package/sax

**Comment by inkz** [comment]
node-expat: https://dev.massive.ret2.co/jobs/1018

**Comment by inkz** [comment]
sax: https://dev.massive.ret2.co/jobs/1017

**Comment by inkz** [comment]
xml2json: https://dev.massive.ret2.co/jobs/1030

**Comment by inkz** [comment]
@minusworld 
I guess that’s it for now, I'll do some triaging but checks are created, so we can close this task

**Comment by minusworld** [comment]
@inkz Sounds good! 👍  These look legit 😎

**Comment by inkz** [comment]
:+1:
