### ISSUE TITLE
[Check] XXE checks for Golang

### ISSUE THREAD

**Issue by minusworld** [returntocorp/semgrep-rules#510]
**Check Description**
XXE checks for Golang, if applicable.

- [x] This ticket has links, references, or examples.
- [ ] Your check has true positive and true negative test cases.
- [ ] Your check has been labeled with true positive and false positive findings on at least 10 repositories, and the link is pasted in the ticket. If there are no findings, paste the triager link anyway.
- [ ] Your check PR has been reviewed and merged.
Now, close the ticket!

**Comment by minusworld** [comment]
Looks like XML External Entities are not supported in the Go standard library:
https://www.reddit.com/r/golang/comments/f0c0wy/are_xml_external_entities_supported_in_encodingxml/

However, a good flag is that Go supports some bindings for `libxml` (also highlighted in the discussion).

https://pkg.go.dev/search?q=libxml

We could scan to see if any of these are commonly used and write detections for the most common ones.

**Comment by ulziibay** [comment]
XXE in Go is hard.

Per https://hackwithpassion.com/index.php/2020/02/10/xxes-in-golang-are-surprisingly-hard/, XXE using `encoding/xml`, which is the default XML package in go, is near impossible.

Even for some popular `libxml2` binding libraries like https://pkg.go.dev/github.com/moovweb/gokogiri,  XXE is hard because the authors were aware of XXE and has disabled entities access:
> // Note that this library assumes you already know the name of entity and does not
> // expose any way of getting the list of entities.

We can further investigate lestrrat-go/libxml2, which seem to expose the accessors for `EntityNode`, however this pkg is unpopular as it is  imported only 4 times on Go pkg registry.

Unless we want to write rules for other obscure, not popular libxml2 go bindings from https://github.com/search?l=Go&q=libxml&type=Repositories, there is not much to do for XXE for golang.


This is what happens when language designers have security in mind :)! 
Cc: @minusworld @inkz

**Comment by ulziibay** [comment]
Closing this ticket as the investigation is over!
